In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("spotify_millsongdata.csv")

In [3]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [4]:
df.tail(5)

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [5]:
df.shape

(57650, 4)

In [6]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [7]:
df = df.sample(5000).drop( 'link' , axis=1 ).reset_index(drop = True )

In [8]:
df.head(5)

,artist,song,text
0,Alabama,Down Home,Just off of the beaten path \r\nA little dot ...
1,America,Emma,I was falling for some time \r\nPassing other...
2,David Guetta,Like A Machine,Can't hear you baby \r\nHey hey what you say?...
3,Richard Marx,Superstar,You're the queen of your own little \r\nWorld...
4,The Beatles,I Feel Fine,"Baby's good to me, you know, \r\nShe's happy ..."

In [9]:
df.tail(5)

,artist,song,text
4995,Rihanna,Mad House,Ladies and gentlemen \r\nTo those among you ...
4996,Unearth,To The Ground,To the ground \r\nSet it all ablaze \r\nThis...
4997,Steely Dan,Pretzel Logic,I would love to tour the Southland \r\nIn a t...
4998,Ice Cube,My Skin Is My Sin,"Motherfucker, you'd better break yourself \r\..."
4999,Queen Adreena,Desert Lullaby,"How, how did I get here \r\nWhat world is thi..."

In [10]:
df['text'][0]

"Just off of the beaten path  \r\nA little dot on a state road map  \r\nThat's where I was born and where I'll die  \r\nThings move at a slower pace  \r\nNobody's in the rat race  \r\nAnd these days that's a special way of life  \r\n  \r\n[Chorus]  \r\nDown home, where they know you by name  \r\nAnd treat you like family  \r\nDown home, a man's good word and hand shake  \r\nAre all you need  \r\nFolks know if they're falling on hard times  \r\nThey can fall back on  \r\nThose of us raised up down home  \r\n  \r\nIn the corner of the hardware store  \r\nGathered 'round a checkerboard  \r\nOld men telling lies and crowning kings  \r\nKids driving 'round the old town square  \r\nTops rolled down in the cool night air  \r\nGo and see what's shaking at the Dairy Queen  \r\n  \r\n[Chorus]  \r\n  \r\nWhen I was a boy, I couldn't wait to leave this place  \r\nBut now I want to see my children raised down home, down home  \r\n  \r\nFolks know if they're falling on hard times  \r\nThey can fall back on  \r\nThose of us raised up...  \r\n  \r\n[Chorus]\r\n\r\n"

In [11]:
df.shape

(5000, 3)

In [12]:
df['text'].str.lower().replace(r'\w\s',' ').replace(r'\n',' ',regex=True)

0       just off of the beaten path  \r a little dot o...
1       i was falling for some time  \r passing others...
2       can't hear you baby  \r hey hey what you say? ...
3       you're the queen of your own little  \r world,...
4       baby's good to me, you know,  \r she's happy a...
                              ...
4995    ladies and gentlemen  \r to those among you  \...
4996    to the ground  \r set it all ablaze  \r this d...
4997    i would love to tour the southland  \r in a tr...
4998    motherfucker, you'd better break yourself  \r ...
4999    how, how did i get here  \r what world is this...
Name: text, Length: 5000, dtype: object

In [13]:
df.tail(5)

,artist,song,text
4995,Rihanna,Mad House,Ladies and gentlemen \r\nTo those among you ...
4996,Unearth,To The Ground,To the ground \r\nSet it all ablaze \r\nThis...
4997,Steely Dan,Pretzel Logic,I would love to tour the Southland \r\nIn a t...
4998,Ice Cube,My Skin Is My Sin,"Motherfucker, you'd better break yourself \r\..."
4999,Queen Adreena,Desert Lullaby,"How, how did I get here \r\nWhat world is thi..."

In [14]:
import nltk
from nltk.stem.porter import PorterStemmer
nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/kalppatel/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [15]:
stemmer = PorterStemmer()

In [16]:
def token(text):
    token = nltk.word_tokenize(text)
    result = []
    for w in token:
        result.append(stemmer.stem(w))
    a = result
    return " ".join(a)

In [17]:
print(token("you are lovely ,love"))
print(token("you are beauty , beautiful"))

you are love , love
you are beauti , beauti

In [18]:
result = []
for x in df['text']:
    result.append(token(x))
df['text'] = result
df['text']

0       just off of the beaten path a littl dot on a s...
1       i wa fall for some time pass other , as they '...
2       ca n't hear you babi hey hey what you say ? sa...
3       you 're the queen of your own littl world , yo...
4       babi 's good to me , you know , she 's happi a...
                              ...
4995    ladi and gentlemen to those among you who are ...
4996    to the ground set it all ablaz thi distanc wit...
4997    i would love to tour the southland in a travel...
4998    motherfuck , you 'd better break yourself my s...
4999    how , how did i get here what world is thi how...
Name: text, Length: 5000, dtype: object

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
tfid = TfidfVectorizer(analyzer = 'word' , stop_words = 'english')

In [21]:
matrix = tfid.fit_transform(df['text'])

In [22]:
similar = cosine_similarity(matrix)

In [23]:
similar[0]

array([1.        , 0.02975056, 0.10116867, ..., 0.04576251, 0.04752252,
       0.02677159])

In [35]:
df[df['song'] == 'Mad House'].index[0]

4995

In [51]:
def recommender(song_name):
    idx = df[df['song'] == song_name].index[0]
    distances = similar[idx]
    sorted_indices = sorted(list(enumerate(distances)), key=lambda x: x[1], reverse=True)
    
    recommended_songs = []
    for i in sorted_indices[1:5]:
        recommended_songs.append(df.iloc[i[0]].song)
    
    return recommended_songs

In [53]:
recommender('Mad House')

['Na Na Na', 'Land Of 1000 Dances', 'Friday', 'Love Like A Bomb']

In [69]:
import pickle
pickle.dump(similar,open('similarity.pkl','wb'))
pickle.dump(df,open('df.pkl','wb'))